# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c62d6a953712b2227d2533f36ea6bbe019334b7383a7688f913c4710ae5808f114e819924db578c5614c52619b95643b6d183302ee99684aa7d23208d15c25fc

test:
  secret_key_base: 832382f3f1f4d095a20253dcef34b280add13917b06e99da136ad9ef930494c4aec9a19974f10328b33b53bfea5f612da33f89dbbeb83cd44e02c1e0f608e3c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
